services:
  backend:
    build:
      context: .
      dockerfile: ./back-go/Dockerfile
    ports:
    - "8080:8080"
    environment:
      - ADMIN_PASSWORD=secret_password
      - ADMIN_USER=admin
    volumes:
      - db-data:/app/data

volumes:
  db-data:
