services:
  backend:
    build:
      context: ./back-go/
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADMIN_PASSWORD=secret_password
      - ADMIN_USER=admin
      - JWT_SECRET=jwt_secret_token
      - DEV=true
    develop:
      watch:
        - action: sync
          path: ./back-go
          target: /app
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./front-web/
      dockerfile: dev.Dockerfile
    depends_on:
      - backend
    environment:
      - API_PROXY_TARGET=http://backend:8080
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./front-web
          target: /usr/src/app
          ignore: node_modules/
